### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by austroelch57** [jayanta525/openwrt-nanopi-r4s#1]
while compiling i get following error : 

rm -f /home/austroelch/WorkSpace/openwrt-nanopi-r4s/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r4s-rk3399/u-boot-2020.07/.configured_*
rm -f /home/austroelch/WorkSpace/openwrt-nanopi-r4s/staging_dir/target-aarch64_generic_musl/stamp/.uboot-rockchip.nanopi-r4s-rk3399_installed
make  -C /home/austroelch/WorkSpace/openwrt-nanopi-r4s/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r4s-rk3399/u-boot-2020.07 USE_PRIVATE_LIBGCC=yes nanopi-r4s-rk3399_config
make[4]: Entering directory '/home/austroelch/WorkSpace/openwrt-nanopi-r4s/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r4s-rk3399/u-boot-2020.07'
***
*** Can't find default configuration "arch/../configs/nanopi-r4s-rk3399_defconfig"!
***
make[5]: *** [scripts/kconfig/Makefile:110: nanopi-r4s-rk3399_defconfig] Error 1
make[4]: *** [Makefile:565: nanopi-r4s-rk3399_config] Error 2
make[4]: Leaving directory '/home/austroelch/WorkSpace/openwrt-nanopi-r4s/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r4s-rk3399/u-boot-2020.07'
make[3]: *** [Makefile:110: /home/austroelch/WorkSpace/openwrt-nanopi-r4s/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r4s-rk3399/u-boot-2020.07/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 2
make[3]: Leaving directory '/home/austroelch/WorkSpace/openwrt-nanopi-r4s/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/nanopi-r4s-rk3399/compile#0.41#0.58#0.84
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r4s-rk3399).
make[2]: *** [package/Makefile:114: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/home/austroelch/WorkSpace/openwrt-nanopi-r4s'
make[1]: *** [package/Makefile:108: /home/austroelch/WorkSpace/openwrt-nanopi-r4s/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/austroelch/WorkSpace/openwrt-nanopi-r4s'
make: *** [/home/austroelch/WorkSpace/openwrt-nanopi-r4s/include/toplevel.mk:242: world] Error 2

any hints ?

Regards from Tyrol/Austria Stephan

**Comment by jayanta525** [comment]
Hi @austroelch57 

This repo for the NanoPi R4S isn't ready yet, as the 1GB version and 4GB version uses different DDR RAM types.

There's a workaround provided by FriendlyARM, but I am testing a more cleaner way to have this done.
